name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Create .ssh Directory
      run: mkdir -p /home/runner/.ssh

    - name: Add SSH Key
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "$EC2_KEY" > /home/runner/.ssh/id_rsa
        chmod 600 /home/runner/.ssh/id_rsa

    - name: Add EC2 Host to known_hosts
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        if [ -z "$EC2_HOST" ]; then
          echo "EC2_HOST is not set. Exiting."
          exit 1
        fi
        ssh-keyscan -H $EC2_HOST >> /home/runner/.ssh/known_hosts

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        if [ -z "$EC2_HOST" ] || [ -z "$EC2_USER" ]; then
          echo "EC2_HOST or EC2_USER is not set. Exiting."
          exit 1
        fi
        scp -i /home/runner/.ssh/id_rsa index.nginx-debian.html $EC2_USER@$EC2_HOST:/home/$EC2_USER/index.nginx-debian.html
        ssh -i /home/runner/.ssh/id_rsa $EC2_USER@$EC2_HOST "sudo mv /home/$EC2_USER/index.nginx-debian.html /var/www/html/index.nginx-debian.html && sudo systemctl restart nginx"
