name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    # .ssh Dizini Yaratma
    - name: Create .ssh Directory
      run: mkdir -p /home/runner/.ssh

    # SSH Anahtarını Yaratma ve İzin Ayarlama
    - name: Add SSH Key
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "$EC2_KEY" > /home/runner/.ssh/id_rsa
        chmod 600 /home/runner/.ssh/id_rsa

    # known_hosts Dosyasına EC2 Anahtarını Eklemek için ssh-keyscan Kullanımı
    - name: Add EC2 Host to known_hosts
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: ssh-keyscan -H $EC2_HOST >> /home/runner/.ssh/known_hosts

    # EC2 Sunucusuna Bağlanma ve Dosya Aktarımı
    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        scp -i /home/runner/.ssh/id_rsa index.nginx-debian.html $EC2_USER@$EC2_HOST:/home/$EC2_USER/index.nginx-debian.html
        ssh -i /home/runner/.ssh/id_rsa $EC2_USER@$EC2_HOST "sudo mv /home/$EC2_USER/index.nginx-debian.html /var/www/html/index.nginx-debian.html && sudo systemctl restart nginx"
``
